// Copyright (c) 2024-2025 Accenture, All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//         http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Description:
// Jenkins pipeline to create Google Compute Engine (GCE) instance templates
// for use with CVD Launcher and CTS Execution jobs.
//
// It reuses the AAOS Docker Builder Docker image, which contains all the
// necessary packages to create the instance template.
pipeline {

  // Parameters defined in groovy/job.groovy
  agent {
    kubernetes {
      yamlMergeStrategy merge()
      yaml """\
        apiVersion: v1
        kind: Pod
        metadata:
          annotations:
            cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
          labels:
            aaos_pod: "true"
        spec:
          tolerations:
          - key: workloadType
            operator: Equal
            value: android
            effect: "NoSchedule"
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: aaos_pod
                    operator: Exists
                topologyKey: kubernetes.io/hostname
          hostname: jenkins-aaos-cf-build-pod
          serviceAccountName: ${JENKINS_SERVICE_ACCOUNT}
          containers:
          - name: builder
            image: ${CLOUD_REGION}-docker.pkg.dev/${CLOUD_PROJECT}/${ANDROID_BUILD_DOCKER_ARTIFACT_PATH_NAME}:latest
            imagePullPolicy: Always
            command:
            - sleep
            args:
            - 5h
            resources:
              limits:
                cpu: 98000m
                memory: 180000Mi
              requests:
                cpu: 98000m
                memory: 180000Mi
          nodeSelector:
            workloadLabel: android
      """.stripIndent()
    }
  }

  stages {
    stage ('Build Cuttlefish image and template (Packer)') {
      when {
        allOf {
          expression { env.DELETE == 'false' }
          expression { env.UPDATE_SSH_AUTHORIZED_KEYS == 'false' }
          expression { env.ANDROID_CUTTLEFISH_REVISION }
        }
      }

      steps {
        container(name: 'builder') {
          script {
            env.MACHINE_TYPE_DESCRIPTION=''
            if ( "${env.MACHINE_TYPE}" != "" ) {
              env.MACHINE_TYPE_DESCRIPTION="${env.MACHINE_TYPE}"
            } else {
              env.MACHINE_TYPE_DESCRIPTION="${env.CUSTOM_VM_TYPE}-custom-${env.CUSTOM_CPU}"
            }
            env.TEMPLATE_TARGET = env.CUTTLEFISH_INSTANCE_NAME ?: env.ANDROID_CUTTLEFISH_REVISION
            currentBuild.description = "Stage: Build image + template" + "<br/>" + "Target: ${env.TEMPLATE_TARGET}" + "<br/>" + "Machine: ${env.MACHINE_TYPE_DESCRIPTION}" + "<br/>" + "$BUILD_USER"
          }
          maskPasswords(varPasswordPairs: [[var: 'REPO_PASSWORD']], varMaskRegexes: []) {
            sh '''
              ADDITIONAL_NETWORKING="${ADDITIONAL_NETWORKING}" \
              BOOT_DISK_SIZE="${BOOT_DISK_SIZE}" \
              BOOT_DISK_TYPE="${BOOT_DISK_TYPE}" \
              CTS_ANDROID_16_URL="${CTS_ANDROID_16_URL}" \
              CTS_ANDROID_15_URL="${CTS_ANDROID_15_URL}" \
              CTS_ANDROID_14_URL="${CTS_ANDROID_14_URL}" \
              CURL_UPDATE_COMMAND=\""${CURL_UPDATE_COMMAND}"\" \
              CUTTLEFISH_POST_COMMAND="${ANDROID_CUTTLEFISH_POST_COMMAND}" \
              CUTTLEFISH_REVISION="${ANDROID_CUTTLEFISH_REVISION}" \
              CUTTLEFISH_URL="${ANDROID_CUTTLEFISH_REPO_URL}" \
              CUTTLEFISH_INSTANCE_NAME="${CUTTLEFISH_INSTANCE_NAME}" \
              CUSTOM_VM_TYPE="${CUSTOM_VM_TYPE}" \
              CUSTOM_CPU="${CUSTOM_CPU}" \
              CUSTOM_MEMORY="${CUSTOM_MEMORY}" \
              JAVA_VERSION="${JAVA_VERSION}" \
              MACHINE_TYPE="${MACHINE_TYPE}" \
              MAX_RUN_DURATION="${MAX_RUN_DURATION}" \
              NODEJS_VERSION="${NODEJS_VERSION}" \
              OS_PROJECT="${OS_PROJECT}" \
              OS_VERSION="${OS_VERSION}" \
              PROJECT=${CLOUD_PROJECT} \
              REGION=${REGION:-${CLOUD_REGION}} \
              REPO_USERNAME="${REPO_USERNAME}" \
              REPO_PASSWORD="${REPO_PASSWORD}" \
              SUBNET=${SUBNET} \
              ZONE=${ZONE:-${CLOUD_ZONE}} \
              ./workloads/android/pipelines/environment/cf_instance_template/cf_create_instance_template.sh 1
            '''
          }
        }
      }
    }

    stage ('Refresh SSH keys on existing template') {
      when {
        allOf {
          expression { env.DELETE == 'false' }
          expression { env.UPDATE_SSH_AUTHORIZED_KEYS == 'true' }
          expression { env.ANDROID_CUTTLEFISH_REVISION || env.CUTTLEFISH_INSTANCE_NAME }
        }
      }

      steps {
        container(name: 'builder') {
          script {
            env.TEMPLATE_TARGET = env.CUTTLEFISH_INSTANCE_NAME ?: env.ANDROID_CUTTLEFISH_REVISION
            currentBuild.description = "Stage: SSH key refresh" + "<br/>" + "Target: ${env.TEMPLATE_TARGET}" + "<br/>" + "$BUILD_USER"
          }
          sh '''
            ADDITIONAL_NETWORKING="${ADDITIONAL_NETWORKING}" \
            BOOT_DISK_TYPE="${BOOT_DISK_TYPE}" \
            CUTTLEFISH_POST_COMMAND="${ANDROID_CUTTLEFISH_POST_COMMAND}" \
            CUTTLEFISH_REVISION="${ANDROID_CUTTLEFISH_REVISION}" \
            CUTTLEFISH_INSTANCE_NAME="${CUTTLEFISH_INSTANCE_NAME}" \
            CUSTOM_VM_TYPE="${CUSTOM_VM_TYPE}" \
            CUSTOM_CPU="${CUSTOM_CPU}" \
            CUSTOM_MEMORY="${CUSTOM_MEMORY}" \
            MACHINE_TYPE="${MACHINE_TYPE}" \
            MAX_RUN_DURATION="${MAX_RUN_DURATION}" \
            OS_PROJECT="${OS_PROJECT}" \
            PROJECT=${CLOUD_PROJECT} \
            REGION=${REGION:-${CLOUD_REGION}} \
            SUBNET=${SUBNET} \
            UPDATE_SSH_AUTHORIZED_KEYS="${UPDATE_SSH_AUTHORIZED_KEYS}" \
            ZONE=${ZONE:-${CLOUD_ZONE}} \
            ./workloads/android/pipelines/environment/cf_instance_template/cf_create_instance_template.sh 2
          '''
        }
      }
    }

    stage ('Delete Cuttlefish artifacts') {

      when {
        allOf {
          expression { env.DELETE == 'true' }
          expression { env.UPDATE_SSH_AUTHORIZED_KEYS == 'false' }
          expression { env.ANDROID_CUTTLEFISH_REVISION || env.CUTTLEFISH_INSTANCE_NAME }
        }
      }

      steps {
        container(name: 'builder') {
          script {
            env.TEMPLATE_TARGET = env.CUTTLEFISH_INSTANCE_NAME ?: env.ANDROID_CUTTLEFISH_REVISION
            currentBuild.description = "Stage: Delete artifacts" + "<br/>" + "Target: ${env.TEMPLATE_TARGET}" + "<br/>" + "$BUILD_USER"
          }
          sh '''
            CUTTLEFISH_REVISION="${ANDROID_CUTTLEFISH_REVISION}" \
            PROJECT=${CLOUD_PROJECT} \
            REGION=${REGION:-${CLOUD_REGION}} \
            CUTTLEFISH_INSTANCE_NAME="${CUTTLEFISH_INSTANCE_NAME}" \
            SUBNET=${SUBNET} \
            ZONE=${ZONE:-${CLOUD_ZONE}} \
            ./workloads/android/pipelines/environment/cf_instance_template/cf_create_instance_template.sh 3
          '''
        }
      }
    }

  }
}
