// Copyright (c) 2024-2026 Accenture, All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//         http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Description:
// AAOS Build targets pipeline.

def getAndroidVersion(revision) {
  if (revision =~ "android-14") {
    return "14"
  } else if (revision =~ "android-15") {
    return "15"
  } else if (revision =~ "android-16") {
    return "16"
  } else {
    currentBuild.result = 'FAILURE'
    error "Failed to determine Android version from revision: ${revision}"
  }
}

pipeline {

  // Parameters defined in groovy/job.groovy

  agent none

  environment {
    GERRIT_API_URL="https://${env.HORIZON_DOMAIN}/gerrit"
    POD_TEMPLATE = "${USE_LOCAL_AOSP_MIRROR == "true" ? kubernetesPodTemplateWithMirror : kubernetesPodTemplateWithoutMirror}"

    def androidVersion="${ANDROID_VERSION != "default" ? ANDROID_VERSION : getAndroidVersion(AAOS_REVISION)}"
    def rpi="${AAOS_LUNCH_TARGET =~ "rpi" ? "-rpi" : ""}"
    SDK_ANDROID_VERSION="${androidVersion}"
    STORAGE_CLASS_SUFFIX="android-${androidVersion}"+"${rpi}"
    STORAGE_SIZE="${STORAGE_CLASS_SUFFIX =~ "rpi" ? "500Gi" : "1000Gi"}"

    // Define Pod Template in environment so we can override storageClassName.

    // Pod template WITHOUT AOSP Mirror volume mounted
    def kubernetesPodTemplateWithoutMirror = """
      apiVersion: v1
      kind: Pod
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        labels:
          aaos_pod: "true"
      spec:
        tolerations:
        - key: workloadType
          operator: Equal
          value: android
          effect: "NoSchedule"
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: aaos_pod
                  operator: Exists
              topologyKey: kubernetes.io/hostname
        hostname: jenkins-aaos-build-pod
        serviceAccountName: ${JENKINS_SERVICE_ACCOUNT}
        containers:
        - name: builder
          image: ${CLOUD_REGION}-docker.pkg.dev/${CLOUD_PROJECT}/${ANDROID_BUILD_DOCKER_ARTIFACT_PATH_NAME}:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
            appArmorProfile:
              type: Unconfined
          command:
          - sleep
          args:
          - 5h
          resources:
            limits:
              cpu: 98000m
              memory: 180000Mi
            requests:
              cpu: 98000m
              memory: 180000Mi
          volumeMounts:
            - mountPath: /aaos-cache
              name: aaos-cache
        volumes:
          - name: aaos-cache
            ephemeral:
              volumeClaimTemplate:
                spec:
                  storageClassName: ${JENKINS_AAOS_BUILD_CACHE_STORAGE_PREFIX}-${STORAGE_CLASS_SUFFIX}
                  resources:
                    requests:
                      storage: ${STORAGE_SIZE}
                  accessModes:
                    - ReadWriteOnce
        nodeSelector:
          workloadLabel: android
    """.stripIndent()

    // Pod template with AOSP Mirror volume mounted as read-only
    def kubernetesPodTemplateWithMirror = """
      apiVersion: v1
      kind: Pod
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        labels:
          aaos_pod: "true"
      spec:
        tolerations:
        - key: workloadType
          operator: Equal
          value: android
          effect: "NoSchedule"
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: aaos_pod
                  operator: Exists
              topologyKey: kubernetes.io/hostname
        hostname: jenkins-aaos-build-pod
        serviceAccountName: ${JENKINS_SERVICE_ACCOUNT}
        containers:
        - name: builder
          image: ${CLOUD_REGION}-docker.pkg.dev/${CLOUD_PROJECT}/${ANDROID_BUILD_DOCKER_ARTIFACT_PATH_NAME}:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
            appArmorProfile:
              type: Unconfined
          command:
          - sleep
          args:
          - 5h
          resources:
            limits:
              cpu: 98000m
              memory: 180000Mi
            requests:
              cpu: 98000m
              memory: 180000Mi
          volumeMounts:
            - mountPath: /aaos-cache
              name: aaos-cache
            - mountPath: ${MIRROR_PRESET_FILESTORE_PVC_MOUNT_PATH_IN_CONTAINER}
              readOnly: true
              name: ${MIRROR_PRESET_FILESTORE_PVC_NAME}
        volumes:
          - name: aaos-cache
            ephemeral:
              volumeClaimTemplate:
                spec:
                  storageClassName: ${JENKINS_AAOS_BUILD_CACHE_STORAGE_PREFIX}-${STORAGE_CLASS_SUFFIX}
                  resources:
                    requests:
                      storage: ${STORAGE_SIZE}
                  accessModes:
                    - ReadWriteOnce
          - name: ${MIRROR_PRESET_FILESTORE_PVC_NAME}
            persistentVolumeClaim:
              claimName: ${MIRROR_PRESET_FILESTORE_PVC_NAME}
        nodeSelector:
          workloadLabel: android
    """.stripIndent()
  }

  stages {
    stage ('Start VM Instance') {
      agent { kubernetes {
        yamlMergeStrategy merge()
        yaml "${POD_TEMPLATE}"
      } }
      stages {
        stage ('Clean') {
          when {
            allOf {
              expression { env.AAOS_LUNCH_TARGET }
              expression { env.AAOS_CLEAN != 'NO_CLEAN' }
            }
          }
          steps {
            script {
              currentBuild.description = "${env.AAOS_LUNCH_TARGET}" + "<br/>" + "${env.AAOS_REVISION}" + "<br/>" + "$BUILD_USER"
            }
            container(name: 'builder') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                sh '''
                  AAOS_LUNCH_TARGET="${AAOS_LUNCH_TARGET}" \
                  AAOS_CLEAN="${AAOS_CLEAN}" \
                  ./workloads/android/pipelines/builds/aaos_builder/aaos_environment.sh
                '''
              }
            }
          }
        }

        stage ('Initialise') {
          when {
            allOf {
              expression { env.AAOS_LUNCH_TARGET }
              expression { currentBuild.currentResult == 'SUCCESS' }
            }
          }
          steps {
            script {
              currentBuild.description = "${env.AAOS_LUNCH_TARGET}" + "<br/>" + "${env.AAOS_REVISION}" + "<br/>" + "$BUILD_USER"
            }
            container(name: 'builder') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                withCredentials([usernamePassword(credentialsId: env.GERRIT_CREDENTIALS_ID, passwordVariable: 'GERRIT_PASSWORD', usernameVariable: 'GERRIT_USERNAME')]) {
                  sh '''
                    set +x
                    echo "AAOS CACHE Persistent Volume Claim: ${NODE_NAME}-aaos-cache" | tee -a build_cache_volume.txt
                    /usr/bin/kubectl get pod ${NODE_NAME} -n jenkins -o=jsonpath='{.spec.nodeName}' | xargs -I {} gcloud compute instances describe {} --zone=${CLOUD_ZONE} | grep 'deviceName: pvc' | awk '{print "AAOS CACHE Persistent Volume: " $2}' | tee -a build_cache_volume.txt || true

                  '''
                  sh '''
                    git config --global credential.helper store
                    git config --global url."https://${GERRIT_USERNAME}@${HORIZON_DOMAIN}/gerrit".insteadOf "https://${HORIZON_DOMAIN}/gerrit"
                    echo https://"${GERRIT_USERNAME}":"${GERRIT_PASSWORD}"@"${HORIZON_DOMAIN}/gerrit" > ~/.git-credentials

                    AAOS_GERRIT_MANIFEST_URL="${AAOS_GERRIT_MANIFEST_URL}" \
                    AAOS_REVISION="${AAOS_REVISION}" \
                    AAOS_LUNCH_TARGET="${AAOS_LUNCH_TARGET}" \
                    AAOS_CLEAN="NO_CLEAN" \
                    GERRIT_SERVER_URL="${GERRIT_API_URL}" \
                    GERRIT_USERNAME="${GERRIT_USERNAME}" \
                    GERRIT_PASSWORD="${GERRIT_PASSWORD}" \
                    POST_REPO_INITIALISE_COMMAND="${POST_REPO_INITIALISE_COMMAND}" \
                    POST_REPO_COMMAND="${POST_REPO_COMMAND}" \
                    REPO_SYNC_JOBS="${GERRIT_REPO_SYNC_JOBS}" \
                    USE_LOCAL_AOSP_MIRROR="${USE_LOCAL_AOSP_MIRROR}" \
                    MIRROR_DIR_FULL_PATH="${MIRROR_PRESET_FILESTORE_PVC_MOUNT_PATH_IN_CONTAINER}/${MIRROR_PRESET_MIRROR_ROOT_SUBDIR_NAME}/${AOSP_MIRROR_DIR_NAME}" \
                    ./workloads/android/pipelines/builds/aaos_builder/aaos_initialise.sh
                  '''
                }
              }
              archiveArtifacts artifacts: 'build_cache*.txt', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: true
            }
          }
        }

        stage ('Build'){
          when {
            allOf {
              expression { env.AAOS_LUNCH_TARGET }
              expression { currentBuild.currentResult == 'SUCCESS' }
            }
          }
          steps {
            container(name: 'builder') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                sh '''
                  AAOS_LUNCH_TARGET="${AAOS_LUNCH_TARGET}" \
                  AAOS_BUILD_CTS=${AAOS_BUILD_CTS} \
                  ./workloads/android/pipelines/builds/aaos_builder/aaos_build.sh
                '''
              }
              archiveArtifacts artifacts: 'aaos-build*.log', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: true
            }
          }
        }

        stage ('AI Review'){
          when {
            allOf {
              expression { env.AAOS_LUNCH_TARGET }
              expression { env.ENABLE_GEMINI_AI_ASSISTANT == 'true' }
              expression { currentBuild.currentResult == 'FAILURE' }
            }
          }
          steps {
            container(name: 'builder') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                sh '''
                  set +ex
                  export GEMINI_ANALYSIS_PATH="/aaos-cache/aaos_builds"
                  echo "Analysis path: ${GEMINI_ANALYSIS_PATH}"
                  # Copy artifacts so Gemini can analyse the source in situ (avoid workspace security issues).
                  cp -f aaos-build*.* "${GEMINI_ANALYSIS_PATH%/}/" || true
                  cd "${GEMINI_ANALYSIS_PATH%/}" || true
                  [ -f aaos-build.log ] && tail -n 2500 aaos-build.log > aaos-build.log.tail || true
                  export GEMINI_PROMPT_FILE="${WORKSPACE}/workloads/android/pipelines/builds/aaos_builder/prompt/sequenced/step1_triage.txt"
                  export GEMINI_PROMPT_FILE_2="${WORKSPACE}/workloads/android/pipelines/builds/aaos_builder/prompt/sequenced/step2_rca.txt"
                  export GEMINI_PROMPT_FILE_3="${WORKSPACE}/workloads/android/pipelines/builds/aaos_builder/prompt/sequenced/step3_fixes.txt"
                  export GEMINI_STEP2_PRIOR_CONTEXT_BYTES="${GEMINI_STEP2_PRIOR_CONTEXT_BYTES:-131072}"
                  export GEMINI_PREVIEW_FEATURES="${GEMINI_PREVIEW_FEATURES}"
                  [ "$GEMINI_LOCATION_GLOBAL" = "true" ] && export GOOGLE_CLOUD_LOCATION="global" || export GOOGLE_CLOUD_LOCATION="${CLOUD_REGION}"
                  export GOOGLE_CLOUD_PROJECT="${CLOUD_PROJECT}"
                  export GEMINI_COMMAND_LINE="${GEMINI_COMMAND_LINE}"
                    "${WORKSPACE}"/workloads/common/agentic-ai/gemini/gemini_initialise.sh
                    timeout "${GEMINI_AI_EXECUTION_TIMEOUT}"h "${WORKSPACE}"/workloads/common/agentic-ai/gemini/gemini_analysis.sh
                    GEMINI_EXIT_CODE=$?

                    echo "Check artifacts create in gemini-assist"
                    ls -la ${GEMINI_ANALYSIS_PATH}/gemini-assist || true

                    # Restore order to cache/PV and workspace.
                    # Avoid gemini deafness and it applying changes, cleanup!
                    repo forall -c 'git checkout -- .; git clean -xfd;' >/dev/null 2>&1
                    rm -f aaos-build*.*

                    cd - || true
                    bash -c 'source \"${WORKSPACE}/workloads/common/agentic-ai/gemini/gemini_environment.sh\" && \
                             move_gemini_artifacts \"${GEMINI_ANALYSIS_PATH%/}\" \"${WORKSPACE}\"' || true

                    find . -type f -name "headless*.json" -size 0 -delete

                    # Fail stage if gemini-client-error.zip exists (CLI error even when exit code was 0)
                    if [ -f "${GEMINI_ANALYSIS_PATH}/gemini-client-error.zip" ] || [ -f "${WORKSPACE}/gemini-client-error.zip" ]; then
                      echo "ERROR: Gemini AI assistant reported errors (gemini-client-error.zip present)"
                      GEMINI_EXIT_CODE=1
                    fi

                    set -e
                    exit ${GEMINI_EXIT_CODE}
                  '''
              }
              archiveArtifacts artifacts: 'gemini-assist/*', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: true
              archiveArtifacts artifacts: 'headless_output*.json', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: false
              script {
                if (fileExists('gemini-client-error.zip')) {
                  archiveArtifacts artifacts: 'gemini-client-error.zip', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: true
                }
              }
            }
          }
        }

        stage ('Storage') {
          when {
            allOf {
              expression { env.AAOS_LUNCH_TARGET }
              expression { env.AAOS_ARTIFACT_STORAGE_SOLUTION }
              anyOf {
                expression { currentBuild.currentResult == 'SUCCESS' }
                expression { env.ENABLE_GEMINI_AI_ASSISTANT == 'true' }
              }
            }
          }
          steps {
            container(name: 'builder') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                script {
                  env.AAOS_BUILD_STAGE_FAILED = (currentBuild.currentResult != 'SUCCESS') ? 'true' : 'false'
                }
                sh '''
                  if [ "${AAOS_BUILD_STAGE_FAILED}" != "true" ]; then
                    AAOS_LUNCH_TARGET="${AAOS_LUNCH_TARGET}" \
                    AAOS_REVISION="${AAOS_REVISION}" \
                    ANDROID_VERSION="${SDK_ANDROID_VERSION}" \
                    ./workloads/android/pipelines/builds/aaos_builder/aaos_avd_sdk.sh || true
                  fi

                  AAOS_LUNCH_TARGET="${AAOS_LUNCH_TARGET}" \
                  AAOS_ARTIFACT_ROOT_NAME="${ANDROID_BUILD_BUCKET_ROOT_NAME}" \
                  AAOS_ARTIFACT_STORAGE_SOLUTION="${AAOS_ARTIFACT_STORAGE_SOLUTION}" \
                  STORAGE_BUCKET_DESTINATION="${STORAGE_BUCKET_DESTINATION}" \
                  STORAGE_LABELS="${STORAGE_LABELS}" \
                  ENABLE_GEMINI_AI_ASSISTANT="${ENABLE_GEMINI_AI_ASSISTANT}" \
                  AAOS_BUILD_STAGE_FAILED="${AAOS_BUILD_STAGE_FAILED}" \
                  ./workloads/android/pipelines/builds/aaos_builder/aaos_storage.sh
                '''
                archiveArtifacts artifacts: '*artifacts*.txt', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: true
              }
            }
          }
        }

        stage ('Retain instance') {
          when { expression { env.AAOS_LUNCH_TARGET } }
          steps {
            container(name: 'builder') {
              script {
                sleep(time: "${INSTANCE_RETENTION_TIME}", unit: 'MINUTES')
              }
            }
          }
        }
      }
    }
  }
}
